name: A workflow for Group 1's Project
on: push

jobs:
  build:
    name: SEM-Group-Project action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build Docker Images
        run: |
          docker build -t sem-group-project-app .
          docker build -t sem-group-project-db ./db
      - name: Run Containers
        run: |
          docker run --name sem-group-project-db-1 -d sem-group-project-db
          docker run --name sem-group-project-app-1 --link sem-group-project-db-1 -d sem-group-project-app
      - name: View Logs
        run: |
          docker logs sem-group-project-app-1
