name: A workflow for Group 1's Project
on: push

jobs:
  build:
    name: SEM-Group-Project action
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package
    - name: Run unit tests
      run: mvn -Dtest=com.napier.sem.CountryTest
    - name: Package and Run docker compose
      run: |
        mvn package -DskipTests
        docker-compose up --abort-on-container-exit